  # TODO-04: Set the spring.application.name to "Lab4 OpenAI Functions" or something similar.
  # Set this application as a non-web application using spring.main.web-application-type: none.
  # Disable the automatic retry mechanism using spring.ai.retry.max-attempts: 1.
  # Note that there are various properties we can set here, including credentials,
  # but we never want to commit credentials to source control.

spring:
  application.name: Lab4 OpenAI Functions
  main.web-application-type: none     # Do not start a web server.

  ai:
    openai:
      api-key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
      on-client-errors: false   # If false, throw a NonTransientAiException, and do not attempt retry for 4xx client error codes.
