spring:
  application.name: Lab2 Azure
  main.web-application-type: none     # Do not start a web server.

  ai:
    azure:
      openai:
        endpoint: ENDPOINT-GOES-HERE
        chat.options.deployment-name: DEPLOYMENT-NAME-GOES-HERE
        chat.options.model: gpt-35-turbo        
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
      on-client-errors: false   # If false, throw a NonTransientAiException, and do not attempt retry for 4xx client error codes.