# TODO-04: Set the spring.application.name to "Lab02 Chat Ollama" or something similar.
# Set the spring.main.web-application-type to none to avoid starting a web server.
# Set the spring.ai.retry.max-attempts to 1 to limit the number of retry attempts.
# Set the spring.ai.ollama.base-url to http://localhost:11434, unless your container is running on a different URL.

spring:
  application.name: Lab2 Chat
  main.web-application-type: none     # Do not start a web server.

