# TODO-03: Set the spring.application.name to "Lab6 Embedding" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set the model-specific attributes according to the lab instructions.
# Take advantage of YAML's hierarchical structure (indenting) to set these values.

spring:
  application.name: Lab6 Embedding
  main.web-application-type: none     # Do not start a web server.

  ai:
    openai.embedding.enabled: false   # Allow profile to enable this if needed.
    ollama.embedding.enabled: false   # Allow profile to enable this if needed.
    embedding.transformer.enabled: false  # SpringAI provides a default embeddings model.  Disable this to force the use of a different model.
    retry:
      max-attempts: 1      # Maximum number of retry attempts.

---
spring:
  config.activate.on-profile: openai

# TODO-03: Set the spring.application.name to "Lab6 Embedding OpenAI" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set ai.openai.embedding.options.model to text-embedding-ada-002.
# Take advantage of YAML's hierarchical structure (indenting) to set these values.

  ai:
    openai:
      embedding:
        enabled: true
        options:
          model: text-embedding-ada-002

---
spring:
  config.activate.on-profile: aws-cohere
  
# TODO-03: Set the spring.application.name to "Lab6 Embedding Bedrock Cohere" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set ai.bedrock.aws.region to "us-west-2", or whichever region you have enabled the titan model in.
# Set ai.bedrock.cohere.embedding.enabled to specify use of the Cohere embedding model.
# Set ai.bedrock.cohere.embedding.model to cohere.embed-english-v3, or whatever value matches your enabled model.
# Take advantage of YAML's hierarchical structure (indenting) to set these values.

  ai:
    bedrock:
      aws.region: us-west-2   # Warning: must be explicitly set even if ~/.aws/config is set.
      cohere:
        embedding:
          enabled: true
          model: cohere.embed-english-v3

---
spring:
  config.activate.on-profile: aws-titan

# TODO-03: Set the spring.application.name to "Lab6 Embedding Bedrock Titan" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set ai.bedrock.aws.region to "us-west-2", or whichever region you have enabled the titan model in.
# Set ai.bedrock.titan.embedding.enabled to specify use of the Titan embedding model.
# Set ai.bedrock.titan.embedding.model to amazon.titan-embed-text-v1, or whatever value matches your enabled model.
# Take advantage of YAML's hierarchical structure (indenting) to set these values.

  ai:
    bedrock:
      titan:
        embedding:
          enabled: true
          model: amazon.titan-embed-text-v1

---
spring:
  config.activate.on-profile: ollama

# TODO-03: Set the spring.application.name to "Lab6 Embedding Ollama" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set ai.ollama.embedding.enabled to specify use of an embedding model.
# Set the ai.ollama.base-url to http://localhost:11434, unless your container is running on a different URL.

  ai:
    ollama:
      base-url: http://localhost:11434  # Default base URL when you run Ollama from Docker
      embedding:
        enabled: true

---
spring:
  config.activate.on-profile: internal

  ai:
    embedding:
      transformer:
        enabled: true

