# TODO-02: Set the spring.application.name to "lab3-images" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set the model-specific attributes according to the lab instructions.
# Take advantage of YAML's hierarchical structure to set these values.
spring:
  application.name: Lab3 Images
  main.web-application-type: none     # Do not start a web server.

  ai:
    retry:
      max-attempts: 1           # Maximum number of retry attempts.

    # Override autoconfiguration so each model needs explicit enablement.
    stabilityai:
      api_key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
      image:
        enabled: false
    zhipuai:
      api_key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
      image:
        enabled: false
    openai:
      api_key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
      image:
        enabled: false
    azure:
      openai:
        api_key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
        image:
          enabled: false

---
spring:
  config.activate.on-profile: openai

  ai:
    openai:
      image:
        enabled: true
        options:
          n: 1                  # Number of images to generate.
          response_format: url  # or b64_json
          size: 1792x1024       # or 1024x1024, 1024x1792
          style: natural        # or vivid

---
spring:
  config.activate.on-profile: azure

  ai:
    azure:
      openai:
        endpoint: ENDPOINT-GOES-HERE
        image:
          enabled: true
          options:
            deployment-name: DEPLOYMENT-NAME-GOES-HERE
            n: 1                  # number of images to generate.
            response_format: url  # or b64_json
            size: 1792x1024       # or 1024x1024, 1024x1792
            style: natural        # or vivid

---
spring:
  config.activate.on-profile: stabilityai

  ai:
    stabilityai:
      image:
        enabled: true
        option:
          n: 1                          # Number of images to generate.
          responseFormat: image/png     # or application/json
          cfg_scale: 8.0                # 0-35, how closely the prompt is followed.
          model: stable-diffusion-v1-6  # The model to use in Stability AI.
          width: 512                    # Must be evenly divisible by 64
          height: 512                   # Must be evenly divisible by 64
          steps: 5                      # Number of diffusion steps to run. Valid range: 10 to 50.

---
spring:
  config.activate.on-profile: zhipuai

  ai:
    zhipuai:
      image:
        enabled: true
