spring:
  application.name: Lab6 VectorStore
  main.web-application-type: none     # Do not start a web server.

  ai:
    openai.embedding.enabled: false   # Allow profile to enable this if needed.
    ollama.embedding.enabled: false   # Allow profile to enable this if needed.
    retry:
      max-attempts: 1      # Maximum number of retry attempts.
    embedding.transformer.enabled: false  # SpringAI provides a default embeddings model.  Disable this to force the use of a different model.

---
spring:
  config.activate.on-profile: openai-embedding
  application.name: Lab6 VectorStore OpenAI

# TODO-01: Set the spring.application.name to "Lab6 VectorStore OpenAI" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set spring.ai.openai.embedding.options.model to text-embedding-ada-002, or see https://platform.openai.com/docs/models/embeddings for latest list.
# Take advantage of YAML's hierarchical structure to set these values.

  ai:
    openai:
      embedding:
        enabled: true
        options:
          model: text-embedding-ada-002

---
spring:
  config.activate.on-profile: aws-cohere-embedding

# TODO-01: Set the spring.application.name to "Lab6 VectorStore Cohere" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set spring.ai.cohere.embedding.enabled to true to switch this embedding model on.
# Set spring.ai.cohere.embedding.model to cohere.embed-english-v3, or see https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html for latest list.
# Take advantage of YAML's hierarchical structure to set these values.

  ai:
    bedrock:
      cohere:
        embedding:
          enabled: true
          model: cohere.embed-english-v3

---
spring:
  config.activate.on-profile: aws-titan-embedding

# TODO-01: Set the spring.application.name to "Lab6 VectorStore Titan" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set spring.ai.titan.embedding.enabled to true to switch this embedding model on.
# Set spring.ai.titan.embedding.model to amazon.titan-embed-text-v1, or see https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html for latest list.
# Take advantage of YAML's hierarchical structure to set these values.

  ai:
    bedrock:
      titan:
        embedding:
          enabled: true
          model: amazon.titan-embed-text-v1

---
spring:
  config.activate.on-profile: ollama-embedding

# TODO-01: Set the spring.application.name to "Lab6 VectorStore Ollama" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Set spring.ai.ollama.embedding.enabled to true to switch this embedding model on.
# Set spring.ai.ollama.base-url to http://localhost:11434 unless you are running Ollama from a different URL.
# Take advantage of YAML's hierarchical structure to set these values.

  ai:
    ollama:
      base-url: http://localhost:11434  # Default base URL when you run Ollama from Docker
      embedding:
        enabled: true

---
spring:
  config.activate.on-profile: simple-vector-store
  
  # If running a simple vector store, exclude the Redis, PGVector, and DataSource autoconfigurations.
  autoconfigure.exclude: 
  - org.springframework.ai.autoconfigure.vectorstore.redis.RedisVectorStoreAutoConfiguration
  - org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---
spring:
  config.activate.on-profile: redis-vector-store

  # TODO-21 (OPTIONAL): Set properties for the Redis vector store.
  # Note that these will only be used if the "redis-vector-store" profile is active.
  # Set spring.ai.vectorstore.redis.uri to redis://localhost:6379, unless your redis is running elsewhere.
  # Set spring.ai.vectorstore.redis.initializeSchema to true to create the necessary schema.
  # (You may not want to do this in a production environment.)
  ai:
    vectorstore:
      redis:
        uri: redis://localhost:6379  # Default.
        index: default-index         # Default.
        prefix: "default:"           # Default.
        initializeSchema: true       # Potentially destructive.

  # If running a redis vector store, exclude the PGVector and DataSource autoconfigurations.
  autoconfigure.exclude: 
  - org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---
spring:
  config.activate.on-profile: pg-vector-store

  # TODO-25 (OPTIONAL): Set properties for the Postgres vector store.
  # Note that these will only be used if the "pg-vector-store" profile is active.
  # Set spring.datasource.url to jdbc:postgresql://localhost:5432/postgres, unless your Postgres is running elsewhere.
  # Set spring.datasource.username and spring.datasource.password the username and password set when running the container.
  # Set the spring.ai.vectorstore.pgvector.initialize-schema to true to create the necessary schema.
  # (You may not want to do this in a production environment.)
  # Set the spring.ai.vectorstore.pgvector.index-type to HNSW.
  # Set the spring.ai.vectorstore.pgvector.distance-type to COSINE_DISTANCE.
  # Set the spring.ai.vectorstore.pgvector.dimensions to 384.  This value is sensitive to the underlying model you are using
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW                # Hierarchical Navigable Small World (HNSW) algorithm, Alternatives: Annoy, LSH, KD-Tree, Ball Tree, Product Quantization, FAISS
        distance-type: COSINE_DISTANCE  # How it determines if one vector is similar to another.
        # CRITICAL: The PGVectorStore database must be initialized to the # of dimensions in the model you are using.
        dimensions: 1536                # OpenAI's text-embedding-ada-002 model uses 1536 dimensions.
        #dimensions: 384                 # AWS/Bedrock/Cohere uses 384 dimensions.

  # If running a simple vector store, exclude the Redis auto configuration.
  autoconfigure.exclude: 
  - org.springframework.ai.autoconfigure.vectorstore.redis.RedisVectorStoreAutoConfiguration

