spring:
  application.name: lab2-aws
  main.web-application-type: none     # Do not start a web server.

  ai:
    bedrock:
      aws.region: us-west-2
      titan:
        chat:
          enabled: true
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
