spring:
  application.name: lab2-ollama
  main.web-application-type: none     # Do not start a web server.

  ai:
    ollama.base-url: http://localhost:11434  # Default base URL when you run Ollama from Docker
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
      on-client-errors: false   # If false, throw a NonTransientAiException, and do not attempt retry for 4xx client error codes.
