  # TODO-04: Set the spring.application.name to "Lab02 Chat AWS" or something similar.
  # Set the spring.main.web-application-type to none to avoid starting a web server.
  # Set the spring.ai.retry.max-attempts to 1 to limit the number of retry attempts.
  # Set the spring.ai.bedrock.aws.region to "us-west-2", or whichever region you have enabled the titan model in.
  # Set the spring.ai.bedrock.titan.chat.enabled to specify use of the Titan chat model.
  
spring:
  application.name: Lab02 
  main.web-application-type: none     # Do not start a web server.
