# TODO-02: Set the spring.application.name to "lab3-images" or something similar.
# Set this application as a non-web application by setting the spring.main.web-application-type to none.
# Disable the automatic retry mechanism by setting the spring.ai.retry.max-attempts to 1.
# Take advantage of YAML's hierarchical structure to set these values.
spring:
  application.name: Lab3 Images
  main.web-application-type: none     # Do not start a web server.

  ai:
    retry:
      max-attempts: 1           # Maximum number of retry attempts.

---
spring:
  config.activate.on-profile: openai

  ai:
    openai:
      image:
        enabled: true
        options:
          n: 1                  # Number of images to generate.
          response_format: url  # or b64_json
          size: 1792x1024       # or 1024x1024, 1024x1792
          style: natural        # or vivid