spring:
  application.name: Lab11 SQL Generation
  main.web-application-type: none     # Do not start a web server.

  ai:
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
      on-client-errors: false   # If false, throw a NonTransientAiException, and do not attempt retry for 4xx client error codes.
    bedrock.anthropic.chat.enabled: false # Disable all models by default.
    ollama.chat.enabled: false        # Disable all models by default.
    openai.chat.enabled: false        # Disable all models by default.
    azure.openai.chat.enabled: false  # Disable all models by default.

---
spring:
  config.activate.on-profile: ollama

  # TODO-02: Set the spring.application.name to "Lab11 SQL Generation with Ollama" or something similar.
  # Set the ai.ollama.base-url to http://localhost:11434, unless your container is running on a different URL.

  application.name: Lab11 SQL Generation with Ollama
  ai:
    ollama:
      base-url: http://localhost:11434  # Default base URL when you run Ollama from Docker
      chat:
        enabled: true
---
spring:
  config.activate.on-profile: aws

  # TODO-02: Set the spring.application.name to "Lab11 SQL Generation with Bedrock" or something similar.
  # Set the ai.bedrock.aws.region to "us-west-2", or whichever region you have enabled the titan model in.
  # Set the ai.bedrock.titan.chat.enabled to specify use of the Titan chat model.
  # Take advantage of YAML's hierarchical structure (indenting) to set these values.
  
  application.name: Lab11 SQL Generation with Bedrock
  ai:
    bedrock:
      aws.region: us-west-2
      anthropic:
        chat:
          enabled: true
          model: anthropic.claude-v2

---
spring:
  config.activate.on-profile: openai

  # TODO-02: Set the spring.application.name to "Lab11 SQL Generation with OpenAI" or something similar.
  # Note that there are various properties we can set here, including credentials,
  # but we never want to commit credentials to source control.
  
  application.name: Lab11 SQL Generation with OpenAI
  ai:
    openai:
      api-key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
      chat:
        enabled: true
        options:
          model: gpt-3.5-turbo


---
spring:
  config.activate.on-profile: azure

  # TODO-02: Set the spring.application.name to "Lab11 Azure OpenAI Chat" or something similar.
  # Set the ai.azure.openai.endpoint to the value you established during Azure setup.
  # Set the ai.azure.openai.chat.enabled to true to enable the chat model.
  # Set the ai.azure.openai.chat.options.deployment-name to the value you establised during setup.
  # Set the ai.azure.openai.chat.options.model to "gpt-35-turbo" to use the GPT-3.5 model.
  # Take advantage of YAML's hierarchical structure (indenting) to set these values.

  application.name: Lab11 SQL Generation with Azure
  ai:
    azure:
      openai:
        api_key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
        endpoint: ENDPOINT-GOES-HERE
        chat:
          enabled: true
          options:
            deployment-name: DEPLOYMENT-NAME-GOES-HERE
            model: gpt-35-turbo        

