spring:
  application.name: lab6-openai-embedding
  main.web-application-type: none     # Do not start a web server.

  ai:
    openai:
      embedding:
        options:
          model: text-embedding-ada-002
    retry:
      max-attempts: 1      # Maximum number of retry attempts.


