  # TDODO-04: Set the spring.application.name to "Lab02 Chat OpenAI" or something similar.
  # Set spring.main.web-application-type to none to run as a non-web application.
  # Set spring.ai.retry.max-attempts to 1 to fail fast.
  # Set spring.ai.retry.on-client-errors to false since there is typically no point in retrying such a request.
  # Set spring.ai.openai.chat.enabled property to true to enable this chatModel.

spring:
  application.name: Lab02 Chat OpenAI
  main.web-application-type: none     # Do not start a web server.

  ai:
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
    openai:
      chat.enabled: true