  # TODO-04: Set the spring.application.name to "Lab02 Chat OpenAI" or something similar.
  # Set the spring.main.web-application-type to none to avoid starting a web server.
  # Set the spring.ai.retry.max-attempts to 1 to limit the number of retry attempts.
  # Set the spring.ai.openai.chat.enabled property to true to enable this chatModel.

spring:
  application.name: Lab2 Chat
  main.web-application-type: none     # Do not start a web server.

